# config.yaml
reference_url: "https://ftp.ensembl.org/pub/release-115/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.15.fa.gz"
reference_dir: "reference"
reference_fa: "reference/Homo_sapiens.GRCh38.dna.chromosome.15.fa"
threads: 6
platform: "ILLUMINA"
samples_tsv: "samples.tsv"
outdir: "results"

